name = "link-uploader"
type = "javascript"

[env.production]
name = "link-uploader"
route = "https://your-worker-name.pages.dev/*"
zone_id = "your-zone-id"

[[kv_namespaces]]
binding = "FILE_STORAGE"
id = "your-namespace-id"
preview_id = "your-preview-namespace-id"
